version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: php_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app_network
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  mariadb:
    image: mariadb:10.6
    container_name: mariadb_db
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:



